"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const { Client } = require("pg");

const integrationUrl = process.env.PRE_TESTE_INTEGRATION_DATABASE_URL || "";

test(
  "PostgreSQL valida cardinalidade e agrega frequências de seleção",
  { skip: !integrationUrl },
  async () => {
    const parsed = new URL(integrationUrl);
    assert.match(parsed.hostname, /^(127\.0\.0\.1|localhost)$/);
    assert.match(parsed.pathname.slice(1), /^escola_preteste_lab_[a-z0-9_]+$/);

    const client = new Client({ connectionString: integrationUrl });
    await client.connect();

    try {
      const identity = await client.query(
        "SELECT current_database() AS database, current_user AS usuario, current_setting('server_version_num')::integer AS versao",
      );
      assert.match(identity.rows[0].database, /^escola_preteste_lab_/);
      assert.ok(identity.rows[0].versao >= 160000);

      await client.query("DROP SCHEMA public CASCADE; CREATE SCHEMA public");
      await client.query(`
        CREATE TABLE public.eventos (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          titulo text NOT NULL
        );
        CREATE TABLE public.usuarios (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          nome text NOT NULL
        );
        CREATE TABLE public.turmas (
          id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
        );
      `);

      for (const migrationName of [
        "2026-08-20-pre-teste-evento.sql",
        "2026-09-01-pre-teste-respostas-multiplas.sql",
      ]) {
        const sql = fs.readFileSync(
          path.resolve(__dirname, `../db/migrations/${migrationName}`),
          "utf8",
        );
        await client.query(`BEGIN;\n${sql}\nCOMMIT;`);
      }

      const evento = await client.query(
        "INSERT INTO eventos (titulo) VALUES ('Evento laboratório') RETURNING id",
      );
      const eventoId = evento.rows[0].id;
      const usuarios = await client.query(
        "INSERT INTO usuarios (nome) SELECT 'Pessoa ' || n FROM generate_series(1, 9) n RETURNING id",
      );
      const preTeste = await client.query(
        "INSERT INTO pre_testes_evento (evento_id, ativo) VALUES ($1, false) RETURNING id",
        [eventoId],
      );
      const versao = await client.query(
        "INSERT INTO pre_teste_versoes (pre_teste_id, numero_versao, status, publicado_em) VALUES ($1, 1, 'publicado', NOW()) RETURNING id",
        [preTeste.rows[0].id],
      );
      const versaoId = versao.rows[0].id;
      await client.query(
        "UPDATE pre_testes_evento SET versao_atual_id = $1, ativo = true WHERE id = $2",
        [versaoId, preTeste.rows[0].id],
      );

      await assert.rejects(
        client.query(
          "INSERT INTO pre_teste_perguntas (versao_id, tipo, modo_resposta, enunciado, ordem) VALUES ($1, 'multipla_escolha', NULL, 'Objetiva sem modo', 90)",
          [versaoId],
        ),
        /pre_teste_perguntas_modo_resposta_check/,
      );
      await assert.rejects(
        client.query(
          "INSERT INTO pre_teste_perguntas (versao_id, tipo, modo_resposta, enunciado, ordem) VALUES ($1, 'multipla_escolha', 'invalido', 'Objetiva inválida', 91)",
          [versaoId],
        ),
        /pre_teste_perguntas_modo_resposta_check/,
      );
      await assert.rejects(
        client.query(
          "INSERT INTO pre_teste_perguntas (versao_id, tipo, modo_resposta, enunciado, ordem) VALUES ($1, 'dissertativa', 'resposta_unica', 'Dissertativa inválida', 92)",
          [versaoId],
        ),
        /pre_teste_perguntas_modo_resposta_check/,
      );

      const perguntaUnica = await client.query(
        "INSERT INTO pre_teste_perguntas (versao_id, tipo, modo_resposta, enunciado, ordem) VALUES ($1, 'multipla_escolha', 'resposta_unica', 'Selecione uma', 2) RETURNING id",
        [versaoId],
      );
      const alternativasUnicas = await client.query(
        "INSERT INTO pre_teste_alternativas (pergunta_id, texto, ordem) VALUES ($1, 'Opção U1', 1), ($1, 'Opção U2', 2) RETURNING id",
        [perguntaUnica.rows[0].id],
      );
      const perguntaDissertativa = await client.query(
        "INSERT INTO pre_teste_perguntas (versao_id, tipo, modo_resposta, enunciado, ordem) VALUES ($1, 'dissertativa', NULL, 'Resposta livre', 3) RETURNING id",
        [versaoId],
      );
      const pergunta = await client.query(
        "INSERT INTO pre_teste_perguntas (versao_id, tipo, modo_resposta, enunciado, ordem) VALUES ($1, 'multipla_escolha', 'respostas_multiplas', 'Selecione uma ou mais opções', 1) RETURNING id",
        [versaoId],
      );
      const perguntaId = pergunta.rows[0].id;
      const alternativas = await client.query(
        "INSERT INTO pre_teste_alternativas (pergunta_id, texto, ordem) VALUES ($1, 'A', 1), ($1, 'B', 2), ($1, 'C', 3), ($1, 'D', 4) RETURNING id, texto",
        [perguntaId],
      );
      const idByText = Object.fromEntries(
        alternativas.rows.map((row) => [row.texto, row.id]),
      );

      const respostas = [
        [idByText.A, idByText.C],
        [idByText.C, idByText.A],
        [idByText.A],
        [idByText.A, idByText.C, idByText.D],
      ];

      for (let index = 0; index < respostas.length; index += 1) {
        const submissao = await client.query(
          "INSERT INTO pre_teste_submissoes (evento_id, versao_id, usuario_id) VALUES ($1, $2, $3) RETURNING id",
          [eventoId, versaoId, usuarios.rows[index].id],
        );
        await client.query(
          "INSERT INTO pre_teste_respostas (submissao_id, pergunta_id, alternativas_ids) VALUES ($1, $2, $3::integer[])",
          [submissao.rows[0].id, perguntaId, respostas[index]],
        );
      }

      const submissaoUnica = await client.query(
        "INSERT INTO pre_teste_submissoes (evento_id, versao_id, usuario_id) VALUES ($1, $2, $3) RETURNING id",
        [eventoId, versaoId, usuarios.rows[4].id],
      );
      await client.query(
        "INSERT INTO pre_teste_respostas (submissao_id, pergunta_id, alternativa_id) VALUES ($1, $2, $3)",
        [
          submissaoUnica.rows[0].id,
          perguntaUnica.rows[0].id,
          alternativasUnicas.rows[0].id,
        ],
      );

      const submissaoDissertativa = await client.query(
        "INSERT INTO pre_teste_submissoes (evento_id, versao_id, usuario_id) VALUES ($1, $2, $3) RETURNING id",
        [eventoId, versaoId, usuarios.rows[5].id],
      );
      await client.query(
        "INSERT INTO pre_teste_respostas (submissao_id, pergunta_id, resposta_texto) VALUES ($1, $2, 'Resposta válida')",
        [submissaoDissertativa.rows[0].id, perguntaDissertativa.rows[0].id],
      );

      const submissaoDuplicada = await client.query(
        "INSERT INTO pre_teste_submissoes (evento_id, versao_id, usuario_id) VALUES ($1, $2, $3) RETURNING id",
        [eventoId, versaoId, usuarios.rows[6].id],
      );
      await assert.rejects(
        client.query(
          "INSERT INTO pre_teste_respostas (submissao_id, pergunta_id, alternativas_ids) VALUES ($1, $2, $3::integer[])",
          [
            submissaoDuplicada.rows[0].id,
            perguntaId,
            [idByText.A, idByText.A, idByText.C],
          ],
        ),
        /valores repetidos/,
      );

      await assert.rejects(
        client.query(
          "INSERT INTO pre_teste_respostas (submissao_id, pergunta_id, alternativas_ids) VALUES ($1, $2, $3::integer[])",
          [
            submissaoDuplicada.rows[0].id,
            perguntaId,
            [idByText.A, alternativasUnicas.rows[0].id],
          ],
        ),
        /não pertencem à pergunta/,
      );

      const submissaoUnicaInvalida = await client.query(
        "INSERT INTO pre_teste_submissoes (evento_id, versao_id, usuario_id) VALUES ($1, $2, $3) RETURNING id",
        [eventoId, versaoId, usuarios.rows[7].id],
      );
      await assert.rejects(
        client.query(
          "INSERT INTO pre_teste_respostas (submissao_id, pergunta_id, alternativas_ids) VALUES ($1, $2, $3::integer[])",
          [
            submissaoUnicaInvalida.rows[0].id,
            perguntaUnica.rows[0].id,
            alternativasUnicas.rows.map((row) => row.id),
          ],
        ),
        /resposta única exige somente alternativa_id/,
      );

      const {
        obterResultados,
      } = require("../src/services/preTesteResultadosService");
      const resultado = await obterResultados(eventoId, versaoId, client);
      const agregada = resultado.perguntas[0];
      const quantidade = Object.fromEntries(
        agregada.alternativas.map((item) => [item.texto, item.quantidade]),
      );

      assert.equal(agregada.total_respostas, 4);
      assert.deepEqual(quantidade, { A: 4, B: 0, C: 3, D: 1 });
      assert.deepEqual(
        Object.fromEntries(
          agregada.alternativas.map((item) => [item.texto, item.percentual]),
        ),
        { A: 100, B: 0, C: 75, D: 25 },
      );
      assert.equal("respostas_corretas" in agregada, false);
    } finally {
      await client.end();
    }
  },
);
