-- Pré-teste diagnóstico, versionado e independente do pós-teste.
--
-- O runner oficial envolve este arquivo em uma transação. Não abrir uma
-- transação própria e não usar CREATE INDEX CONCURRENTLY.

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

DO $preflight_pre_teste$
DECLARE
  v_eventos_id_tipo oid;
  v_usuarios_id_tipo oid;
  v_turmas_id_tipo oid;
BEGIN
  IF to_regclass('public.eventos') IS NULL
     OR to_regclass('public.usuarios') IS NULL
     OR to_regclass('public.turmas') IS NULL THEN
    RAISE EXCEPTION
      'Preflight pre-teste: eventos, usuarios e turmas devem existir';
  END IF;

  IF to_regclass('public.pre_testes_evento') IS NOT NULL
     OR to_regclass('public.pre_teste_versoes') IS NOT NULL
     OR to_regclass('public.pre_teste_perguntas') IS NOT NULL
     OR to_regclass('public.pre_teste_alternativas') IS NOT NULL
     OR to_regclass('public.pre_teste_submissoes') IS NOT NULL
     OR to_regclass('public.pre_teste_respostas') IS NOT NULL THEN
    RAISE EXCEPTION
      'Preflight pre-teste: uma ou mais tabelas de destino já existem; inspeção manual obrigatória';
  END IF;

  SELECT a.atttypid
    INTO v_eventos_id_tipo
    FROM pg_catalog.pg_attribute a
   WHERE a.attrelid = 'public.eventos'::regclass
     AND a.attname = 'id'
     AND a.attnum > 0
     AND NOT a.attisdropped
     AND a.attnotnull;

  SELECT a.atttypid
    INTO v_usuarios_id_tipo
    FROM pg_catalog.pg_attribute a
   WHERE a.attrelid = 'public.usuarios'::regclass
     AND a.attname = 'id'
     AND a.attnum > 0
     AND NOT a.attisdropped
     AND a.attnotnull;

  SELECT a.atttypid
    INTO v_turmas_id_tipo
    FROM pg_catalog.pg_attribute a
   WHERE a.attrelid = 'public.turmas'::regclass
     AND a.attname = 'id'
     AND a.attnum > 0
     AND NOT a.attisdropped
     AND a.attnotnull;

  IF v_eventos_id_tipo IS DISTINCT FROM 'pg_catalog.int4'::regtype
     OR v_usuarios_id_tipo IS DISTINCT FROM 'pg_catalog.int4'::regtype
     OR v_turmas_id_tipo IS DISTINCT FROM 'pg_catalog.int4'::regtype THEN
    RAISE EXCEPTION
      'Preflight pre-teste: IDs de eventos, usuarios e turmas devem ser integer';
  END IF;

  IF NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'public.eventos'::regclass
       AND c.contype = 'p'
       AND pg_get_constraintdef(c.oid, true) = 'PRIMARY KEY (id)'
  ) OR NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'public.usuarios'::regclass
       AND c.contype = 'p'
       AND pg_get_constraintdef(c.oid, true) = 'PRIMARY KEY (id)'
  ) OR NOT EXISTS (
    SELECT 1
      FROM pg_catalog.pg_constraint c
     WHERE c.conrelid = 'public.turmas'::regclass
       AND c.contype = 'p'
       AND pg_get_constraintdef(c.oid, true) = 'PRIMARY KEY (id)'
  ) THEN
    RAISE EXCEPTION
      'Preflight pre-teste: PK simples em id não confirmada nas tabelas-base';
  END IF;
END
$preflight_pre_teste$;

CREATE TABLE public.pre_testes_evento (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  evento_id integer NOT NULL,
  ativo boolean NOT NULL DEFAULT false,
  versao_atual_id integer NULL,
  criado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  atualizado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT pre_testes_evento_pkey PRIMARY KEY (id),
  CONSTRAINT pre_testes_evento_evento_unique UNIQUE (evento_id),
  CONSTRAINT pre_testes_evento_evento_fk
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id) ON DELETE CASCADE,
  CONSTRAINT pre_testes_evento_ativo_versao_check
    CHECK (NOT ativo OR versao_atual_id IS NOT NULL),
  CONSTRAINT pre_testes_evento_id_versao_unique UNIQUE (id, versao_atual_id)
);

CREATE TABLE public.pre_teste_versoes (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  pre_teste_id integer NOT NULL,
  numero_versao integer NOT NULL,
  status text NOT NULL DEFAULT 'rascunho',
  publicado_em timestamp without time zone NULL,
  criado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  atualizado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT pre_teste_versoes_pkey PRIMARY KEY (id),
  CONSTRAINT pre_teste_versoes_pre_teste_numero_unique
    UNIQUE (pre_teste_id, numero_versao),
  CONSTRAINT pre_teste_versoes_pre_teste_id_id_unique
    UNIQUE (pre_teste_id, id),
  CONSTRAINT pre_teste_versoes_pre_teste_fk
    FOREIGN KEY (pre_teste_id)
    REFERENCES public.pre_testes_evento(id)
    ON DELETE CASCADE,
  CONSTRAINT pre_teste_versoes_numero_check CHECK (numero_versao > 0),
  CONSTRAINT pre_teste_versoes_status_check
    CHECK (status IN ('rascunho', 'publicado')),
  CONSTRAINT pre_teste_versoes_publicacao_check
    CHECK (
      (status = 'rascunho' AND publicado_em IS NULL)
      OR (status = 'publicado' AND publicado_em IS NOT NULL)
    )
);

CREATE UNIQUE INDEX pre_teste_versoes_um_rascunho_idx
  ON public.pre_teste_versoes (pre_teste_id)
  WHERE status = 'rascunho';

ALTER TABLE public.pre_testes_evento
  ADD CONSTRAINT pre_testes_evento_versao_atual_fk
  FOREIGN KEY (id, versao_atual_id)
  REFERENCES public.pre_teste_versoes(pre_teste_id, id)
  DEFERRABLE INITIALLY IMMEDIATE;

CREATE TABLE public.pre_teste_perguntas (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  versao_id integer NOT NULL,
  tipo text NOT NULL,
  enunciado text NOT NULL,
  ordem integer NOT NULL,
  criado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  atualizado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT pre_teste_perguntas_pkey PRIMARY KEY (id),
  CONSTRAINT pre_teste_perguntas_versao_fk
    FOREIGN KEY (versao_id)
    REFERENCES public.pre_teste_versoes(id)
    ON DELETE CASCADE,
  CONSTRAINT pre_teste_perguntas_tipo_check
    CHECK (tipo IN ('multipla_escolha', 'dissertativa')),
  CONSTRAINT pre_teste_perguntas_enunciado_check
    CHECK (btrim(enunciado) <> ''),
  CONSTRAINT pre_teste_perguntas_ordem_check CHECK (ordem > 0),
  CONSTRAINT pre_teste_perguntas_versao_ordem_unique UNIQUE (versao_id, ordem),
  CONSTRAINT pre_teste_perguntas_versao_id_id_unique UNIQUE (versao_id, id)
);

CREATE TABLE public.pre_teste_alternativas (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  pergunta_id integer NOT NULL,
  texto text NOT NULL,
  ordem integer NOT NULL,
  criado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  atualizado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT pre_teste_alternativas_pkey PRIMARY KEY (id),
  CONSTRAINT pre_teste_alternativas_pergunta_fk
    FOREIGN KEY (pergunta_id)
    REFERENCES public.pre_teste_perguntas(id)
    ON DELETE CASCADE,
  CONSTRAINT pre_teste_alternativas_texto_check CHECK (btrim(texto) <> ''),
  CONSTRAINT pre_teste_alternativas_ordem_check CHECK (ordem > 0),
  CONSTRAINT pre_teste_alternativas_pergunta_ordem_unique
    UNIQUE (pergunta_id, ordem),
  CONSTRAINT pre_teste_alternativas_pergunta_id_id_unique
    UNIQUE (pergunta_id, id)
);

CREATE TABLE public.pre_teste_submissoes (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  evento_id integer NOT NULL,
  versao_id integer NOT NULL,
  usuario_id integer NOT NULL,
  enviado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  criado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT pre_teste_submissoes_pkey PRIMARY KEY (id),
  CONSTRAINT pre_teste_submissoes_evento_fk
    FOREIGN KEY (evento_id) REFERENCES public.eventos(id),
  CONSTRAINT pre_teste_submissoes_versao_fk
    FOREIGN KEY (versao_id) REFERENCES public.pre_teste_versoes(id),
  CONSTRAINT pre_teste_submissoes_usuario_fk
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id),
  CONSTRAINT pre_teste_submissoes_usuario_evento_versao_unique
    UNIQUE (usuario_id, evento_id, versao_id)
);

CREATE INDEX pre_teste_submissoes_evento_idx
  ON public.pre_teste_submissoes (evento_id, versao_id);

CREATE INDEX pre_teste_submissoes_usuario_idx
  ON public.pre_teste_submissoes (usuario_id, enviado_em DESC);

CREATE TABLE public.pre_teste_respostas (
  id integer GENERATED BY DEFAULT AS IDENTITY,
  submissao_id integer NOT NULL,
  pergunta_id integer NOT NULL,
  alternativa_id integer NULL,
  resposta_texto text NULL,
  criado_em timestamp without time zone NOT NULL DEFAULT NOW(),
  CONSTRAINT pre_teste_respostas_pkey PRIMARY KEY (id),
  CONSTRAINT pre_teste_respostas_submissao_fk
    FOREIGN KEY (submissao_id)
    REFERENCES public.pre_teste_submissoes(id)
    ON DELETE CASCADE,
  CONSTRAINT pre_teste_respostas_pergunta_fk
    FOREIGN KEY (pergunta_id)
    REFERENCES public.pre_teste_perguntas(id),
  CONSTRAINT pre_teste_respostas_alternativa_fk
    FOREIGN KEY (alternativa_id)
    REFERENCES public.pre_teste_alternativas(id),
  CONSTRAINT pre_teste_respostas_submissao_pergunta_unique
    UNIQUE (submissao_id, pergunta_id),
  CONSTRAINT pre_teste_respostas_formato_check
    CHECK (
      (alternativa_id IS NOT NULL AND resposta_texto IS NULL)
      OR (
        alternativa_id IS NULL
        AND resposta_texto IS NOT NULL
        AND btrim(resposta_texto) <> ''
      )
    )
);

CREATE INDEX pre_teste_respostas_pergunta_idx
  ON public.pre_teste_respostas (pergunta_id);

CREATE OR REPLACE FUNCTION public.pre_teste_validar_configuracao_ativa()
RETURNS trigger
LANGUAGE plpgsql
AS $funcao$
BEGIN
  IF NEW.ativo AND NOT EXISTS (
    SELECT 1
      FROM public.pre_teste_versoes v
     WHERE v.id = NEW.versao_atual_id
       AND v.pre_teste_id = NEW.id
       AND v.status = 'publicado'
  ) THEN
    RAISE EXCEPTION
      'Pré-teste ativo exige versão vigente publicada do mesmo evento';
  END IF;

  RETURN NEW;
END
$funcao$;

CREATE TRIGGER pre_testes_evento_validar_ativo_trigger
BEFORE INSERT OR UPDATE OF ativo, versao_atual_id
ON public.pre_testes_evento
FOR EACH ROW
EXECUTE FUNCTION public.pre_teste_validar_configuracao_ativa();

CREATE OR REPLACE FUNCTION public.pre_teste_validar_alternativa()
RETURNS trigger
LANGUAGE plpgsql
AS $funcao$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM public.pre_teste_perguntas p
     WHERE p.id = NEW.pergunta_id
       AND p.tipo = 'multipla_escolha'
  ) THEN
    RAISE EXCEPTION
      'Alternativa exige pergunta do tipo multipla_escolha';
  END IF;

  RETURN NEW;
END
$funcao$;

CREATE TRIGGER pre_teste_alternativas_validar_tipo_trigger
BEFORE INSERT OR UPDATE OF pergunta_id
ON public.pre_teste_alternativas
FOR EACH ROW
EXECUTE FUNCTION public.pre_teste_validar_alternativa();

CREATE OR REPLACE FUNCTION public.pre_teste_validar_submissao()
RETURNS trigger
LANGUAGE plpgsql
AS $funcao$
BEGIN
  IF NOT EXISTS (
    SELECT 1
      FROM public.pre_teste_versoes v
      JOIN public.pre_testes_evento pt ON pt.id = v.pre_teste_id
     WHERE v.id = NEW.versao_id
       AND v.status = 'publicado'
       AND pt.evento_id = NEW.evento_id
  ) THEN
    RAISE EXCEPTION
      'Submissão exige versão publicada pertencente ao evento informado';
  END IF;

  RETURN NEW;
END
$funcao$;

CREATE TRIGGER pre_teste_submissoes_validar_trigger
BEFORE INSERT OR UPDATE OF evento_id, versao_id
ON public.pre_teste_submissoes
FOR EACH ROW
EXECUTE FUNCTION public.pre_teste_validar_submissao();

CREATE OR REPLACE FUNCTION public.pre_teste_validar_resposta()
RETURNS trigger
LANGUAGE plpgsql
AS $funcao$
DECLARE
  v_tipo text;
BEGIN
  SELECT p.tipo
    INTO v_tipo
    FROM public.pre_teste_submissoes s
    JOIN public.pre_teste_perguntas p ON p.versao_id = s.versao_id
   WHERE s.id = NEW.submissao_id
     AND p.id = NEW.pergunta_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION
      'Pergunta não pertence à versão da submissão';
  END IF;

  IF v_tipo = 'multipla_escolha' THEN
    IF NEW.alternativa_id IS NULL OR NEW.resposta_texto IS NOT NULL THEN
      RAISE EXCEPTION
        'Pergunta de múltipla escolha exige somente alternativa_id';
    END IF;

    IF NOT EXISTS (
      SELECT 1
        FROM public.pre_teste_alternativas a
       WHERE a.id = NEW.alternativa_id
         AND a.pergunta_id = NEW.pergunta_id
    ) THEN
      RAISE EXCEPTION
        'Alternativa não pertence à pergunta informada';
    END IF;
  ELSIF v_tipo = 'dissertativa' THEN
    IF NEW.alternativa_id IS NOT NULL
       OR NEW.resposta_texto IS NULL
       OR btrim(NEW.resposta_texto) = '' THEN
      RAISE EXCEPTION
        'Pergunta dissertativa exige somente resposta_texto não vazia';
    END IF;
  ELSE
    RAISE EXCEPTION 'Tipo de pergunta inválido';
  END IF;

  RETURN NEW;
END
$funcao$;

CREATE TRIGGER pre_teste_respostas_validar_trigger
BEFORE INSERT OR UPDATE OF submissao_id, pergunta_id, alternativa_id, resposta_texto
ON public.pre_teste_respostas
FOR EACH ROW
EXECUTE FUNCTION public.pre_teste_validar_resposta();
